// <auto-generated />
using CodVeda_FullStack_Intern.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodVeda_FullStack_Intern.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208142312_AddedBooksAndAdminSeed")]
    partial class AddedBooksAndAdminSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodVeda_FullStack_Intern.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsHidden = false,
                            PublishDate = "2024",
                            Publisher = "CodVeda Press",
                            Summary = "The comprehensive history of how the BookFlow library management system was developed during the internship.",
                            Title = "BookFlow History"
                        },
                        new
                        {
                            Id = 2,
                            IsHidden = false,
                            PublishDate = "2023",
                            Publisher = "University Press",
                            Summary = "Exploring the digital transformation of student connections and resource sharing in academic environments.",
                            Title = "UfsConnectBook History"
                        },
                        new
                        {
                            Id = 3,
                            IsHidden = false,
                            PublishDate = "2025",
                            Publisher = "Tech Pioneers Publishing",
                            Summary = "A deep dive into the journey of Lindele Nyambe, focusing on software engineering milestones and future visions.",
                            Title = "Lindele's History"
                        });
                });

            modelBuilder.Entity("CodVeda_FullStack_Intern.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "System Admin",
                            Password = "&0137Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
